spring:
  application:
    name: post-service
  #  rabbitmq:
  #    host: localhost
  #    port: 5673
  #    username: guest
  #    password: guest
  cloud:
    stream:
      bindings:
        notificationEventSupplier-in-0:
          destination: notification-events
      source: notificationEventSupplier

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
