spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/post-service
  application:
    name: post-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    stream:
      bindings:
        notificationEventSupplier-out-0:
          destination: notification-events
      source: notificationEventSupplier

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/microservices-realm

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}