spring:
  config:
    name: web-service
  application:
    name: web-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

server:
  port: 8082
