spring:
  application:
    name: web-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${random.uuid}

server:
  port: 0
