spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/genre-service
  application:
    name:
      genre-service

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
