spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/post/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**

        - id: genre-service
          uri: lb://genre-service
          predicates:
            - Path=/api/v1/genre/**
      default-filters: TokenRelay

    loadbalancer:
      ribbon:
        enabled: false

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/microservices-realm
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: fc3b3704-3de4-41a5-9d1f-11d715e37a5a
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${random.uuid}